name: befriended_flutter
description: Application to help with Eating Disorder
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  bubble: ^1.2.1
  cloud_firestore: ^3.1.12
  equatable: ^2.0.3
  file_picker: ^4.5.1
  firebase_auth: ^3.3.14
  firebase_core: ^1.14.1
  firebase_database: ^9.0.15
  firebase_messaging: ^11.4.1
  firebase_storage: ^10.2.17
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_chat_ui: 
    path: packages/flutter_chat_ui-main
  flutter_localizations:
    sdk: flutter
  flutter_services_binding: ^0.1.0
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  image_picker: ^0.8.5
  intl: ^0.17.0
  json_annotation: ^4.4.0
  loading_indicator: ^3.0.3
  modal_bottom_sheet: ^2.0.1
  open_file: ^3.2.1
  otp_text_field: ^1.1.2
  overlay_support: ^2.0.1
  page_transition: ^2.0.5
  shared_preferences: ^2.0.13
  simple_animations: ^4.0.1
  uuid: ^3.0.6
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^9.6.0
  timezone:
  rxdart: ^0.27.4
  weekday_selector: ^1.1.0
  string_validator: ^0.3.0
  flutter_tags: ^1.0.0-nullsafety.1

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/countrycodes.json
    - assets/timezones.json
    - assets/messages.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.jpeg"
